@startuml

'Style
skinparam defaultFontName Raleway
!$COLOUR_COMPONENT = "#F2B184"
!$COLOUR_CONTAINER = "#EB843D"
!$COLOUR_PERSON = "#671D47"
!$COLOUR_PERSON_EXT = "#53534A"
!$COLOUR_SYSTEM = "#CB6015"
!$COLOUR_SYSTEM_EXT = "#7C7C6F"
!$COLOUR_NEUTRAL = "#F7F7F7"

UpdateElementStyle("system", $shape=RoundedBoxShape(), $shadowing="true", $legendText="system", $sprite="blur_on")
UpdateElementStyle("external_system", $shape=RoundedBoxShape(), $shadowing="true", $legendText="external system", $sprite="blur_on")
UpdateElementStyle("person", $shape=RoundedBoxShape(), $shadowing="true", $legendText="external system", $sprite="user")
UpdateElementStyle("external_person", $shape=RoundedBoxShape(), $shadowing="true", $legendText="external person", $sprite="user")

AddPersonTag("cyma_person", $bgColor=$COLOUR_PERSON, $fontColor=$COLOUR_NEUTRAL, $sprite="user", $legendText="person")
AddSystemTag("cyma_system", $bgColor=$COLOUR_SYSTEM, $fontColor=$COLOUR_NEUTRAL, $sprite="blur_on", $legendText="system")
AddContainerTag("cyma_container", $bgColor=$COLOUR_CONTAINER, $fontColor=$COLOUR_NEUTRAL, $legendText="container")
AddComponentTag("cyma_component", $bgColor=$COLOUR_COMPONENT, $fontColor=$COLOUR_NEUTRAL, $legendText="component")

@enduml