@startuml

'https://github.com/Roemer/plantuml-office/blob/master/README.md
!define Office https://raw.githubusercontent.com/Roemer/plantuml-office/master/office2014
!includeurl Office/Clouds/cloud_sharepoint_online.puml

'https://github.com/plantuml-stdlib/gilbarbara-plantuml-sprites/blob/master/README.md
!define gilbarbara https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.0/sprites
!include gilbarbara/oracle.puml
!include gilbarbara/salesforce.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-1/dist
!include AzurePuml/Integration/all.puml
!include AzurePuml/Databases/all.puml
!include AzurePuml/Compute/all.puml
!include AzurePuml/AzureCommon.puml

!define iconURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!include iconURL/material/web_asset.puml
!include iconURL/material/list.puml
!include iconURL/material/error_outline.puml
!include iconURL/material/email.puml
!include iconURL/material/blur_on.puml
!include iconURL/font-awesome/window_close.puml
!include iconURL/font-awesome/bank.puml
!include iconURL/font-awesome-5/users.puml
!include iconURL/font-awesome-5/user.puml
!include iconURL/font-awesome-5/snowflake.puml
!include iconURL/font-awesome-5/sms.puml
!include iconURL/font-awesome-5/microsoft.puml
!include iconURL/font-awesome-5/microphone.puml
!include iconURL/font-awesome-5/info_circle.puml
!include iconURL/font-awesome-5/house_damage.puml
!include iconURL/font-awesome-5/hands_helping.puml
!include iconURL/font-awesome-5/code.puml
!include iconURL/font-awesome-5/cloud_download_alt.puml
!include iconURL/font-awesome-5/clock.puml
!include iconURL/font-awesome-5/car.puml
!include iconURL/font-awesome-5/calculator.puml
!include iconURL/font-awesome-5/buffer.puml
!include iconURL/font-awesome-5/arrows_alt.puml
!include iconURL/devicons2/oracle_original.puml
!include iconURL/devicons2/kotlin.puml
!include iconURL/devicons/dotnet.puml
!include iconURL/devicons/database.puml

@enduml