@startuml PPS Integration Landscape
'skinparam monochrome true
'skinparam linetype polyline

'Title "PPS Mutual Application Landscape"

!theme C4_cyma from https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/themes/

'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/sprites.puml
!include https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/brand.puml

LAYOUT_LANDSCAPE()
'LAYOUT_LEFT_RIGHT()
'LAYOUT_AS_SKETCH()

Person_Ext(p_client, "Client", "Professional seeking PPS Mutual services")
Person_Ext(p_advisor, "Advisor", "A qualified financial professional specializing in providing insurance advice to professionals eligible for PPS Mutual membership.", $sprite="user")

Person(p_underwriter, "Underwriter", "Assesses the risk of approving applications for insurance.", $sprite="user")

System_Boundary(sb_underwriting, "Underwriting Solution"){
    System(sys_difftech, "DifferentTechnology", "Integrated digital sales process including automated underwriting (QUIRC Core), dynamic pricing and digital policy initiation.")
    System(sys_quirc, "hr|QUIRC Core", "Hr | QUIRC is an underwriting system specifically designed for the life insurance industry.")
}

'System(sys_dms, "Document Management Solution", "Stores and generates documents", $sprite="cloud_sharepoint_online")
System(sys_sapiens, "Sapiens", "Sapiens Insurance Platform is an AI-powered software solution designed for insurance companies.")

Rel(p_advisor, sys_difftech, "Accesses underwriting service", "https")
Rel(p_client, sys_difftech, "Accesses underwriting services", "https")
Rel_D(p_underwriter, sys_quirc, "Accesses underwriting service", "https")
Rel(sys_difftech, sys_quirc, "Enrich underwriting data", "https")
'Rel(sys_sapiens, sys_dms, "POST medical consent", "https")
Rel(sys_sapiens, sys_quirc, "POST person, application", "https")

SHOW_FLOATING_LEGEND()

@enduml