@startuml PPS Integration Landscape
'skinparam monochrome true
'skinparam linetype polyline

!theme C4_cyma from https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/themes/

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/sprites.puml
!include https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/brand.puml

'LAYOUT_LANDSCAPE()
LAYOUT_LEFT_RIGHT()
LAYOUT_AS_SKETCH()

Person_Ext(p_lead, "Client", "Professional seeking PPS Mutual services")
Person_Ext(p_member, "Member", "A professional who owns a stake in the company and enjoys unique benefits beyond just insurance", $sprite="user")
Person_Ext(p_advisor, "Advisor", "A qualified financial professional specializing in providing insurance advice to professionals eligible for PPS Mutual membership.", $sprite="user")

System_Ext(sys_asb, "ASB", "ASB Banking Services")
'System_Ext(sys_ifrs17, "PWC 17Slved", "Creation of IFRS17 compliant accounts.")
'System_Ext(sys_konnect, "KonnectNET", "The trusted connection between insurance and healthcare.")
System_Ext(sys_paymntgty, "WorldLine", "Provide secure and efficient payment processing solutions for insurance companies, streamlining the way customers pay their premiums.")

Enterprise_Boundary(e0, "PPS Mutual"){
/' Person(p_compliance, "Compliance Officer", "Ensures PPS Mutual adheres to all relevant regulations and industry standards.", $sprite="user")
Person(p_operations, "Operations", "Provide essential support to various departments within PPS Mutual, ensuring smooth day-to-day functioning.", $sprite="users")
Person(p_underwriter, "Underwriter", "Assesses the risk of approving applications for insurance.", $sprite="user")
 '/
System_Boundary(sb_processapi, "Process API"){
System(sys_documentsvc, "Document Service", "Provides document services", $tags="api")
System(sys_mediasvc, "Media Service", "Provides media services to support storing and retrieval media.", $tags="api")
System(sys_notifysvc, "Notification Service", "Provides Notification Services", $tags="api")
System(sys_policysvc, "Policy Service", "Provides Policy Services", $tags="api")
System(sys_pymntsvc, "Payment Service", "Provides abstraction for payment services", $tags="api")
System(sys_quotesvc, "Quote Service", "Provides Quote Services", $tags="api")
System(sys_sanctionsvc, "Sanctions Service", "Solution that holds the OFAC & UN lists.", $tags="api")
}

System_Boundary(sb_underwriting, "Underwriting"){
    System(sys_difftech, "DifferentTechnology", "Digital self-service for both sales and servicing as a core design philosophy not an afterthought.")
    System(sys_quirc, "hr|QUIRC", "Hr | QUIRC is an automated underwriting system specifically designed for the life insurance industry")
}

System(sys_amlhub, "AML Hub", "Provdes tools, resources, and data to help identify and stop money laundering.")
System(sys_dataplatform, "Data Platform [TBC]", "Data Platform is a cloud-based platform that unifies data, analytics, and artificial intelligence (AI) for businesses.")
System(sys_dms, "Document Management Solution", "Stores and generates documents")
System(sys_dynamics, "Business Central", "Microsoft Dynamics 365 Business Central is an all-in-one business management solution designed for small and medium-sized businesses (SMBs).")
System(sys_glextract, "GL Service", "Provides Daily GL extracts from Sapiens et al.,", $tags="api")
System(sys_sanction, "Sanctions Screening Tool", "Solution that holds the OFAC & UN lists.")
System(sys_sapiens, "Sapiens", "Sapiens Insurance Platform is an AI-powered software solution designed for insurance companies.")
System(sys_telephony, "Operational Telephony", "A phone system for various purposes such as supporting advisors with policy inquiries and servicing member needs.")
}

Rel(p_advisor, p_lead, "Engages with lead")
/' Rel(p_advisor, sys_difftech, "Accesses underwriting services", "https")
Rel(p_advisor, sys_konnect, "Accesses medical data", "https")
Rel(p_advisor, sys_sapiens, "Accesses advisor portal", "https")
Rel(p_compliance, sys_amlhub, "Accesses AML service", "https")
Rel(p_compliance, sys_sanction, "Accesses sanction service", "https")
Rel(p_compliance, sys_sapiens, "Accesses Sapiens services", "https")
Rel(p_member, sys_sapiens, "Accesses member portal", "https")
Rel(p_operations, sys_sanction, "Process New Business", "https")
Rel(p_operations, sys_sapiens, "Accesses Sapiens service", "https")
Rel(p_operations, sys_telephony, "Accesses to manage calls", "pstn")
Rel(p_underwriter, sys_difftech, "Accesses underwriting service", "https")
Rel(p_underwriter, sys_sapiens, "Accesses Sapiens service", "https") '/
Rel(sys_dataplatform, sys_sapiens, "ETL Policy Administration data", "???")
Rel(sys_difftech, sys_quirc, "GET|PUT underwriting data", "https")
Rel(sys_documentsvc, sys_dms, "POST|GET document", "https")
Rel(sys_dynamics, sys_dataplatform, "ETL Financial data", "???")
Rel(sys_glextract, sys_dynamics, "POST GL data", "https")
Rel(sys_policysvc, sys_documentsvc, "POST|GET policy document", "https")
Rel(sys_policysvc, sys_notifysvc, "POST notification", "https")
Rel(sys_pymntsvc, sys_asb, "POST banking payments", "sftp")
Rel(sys_pymntsvc, sys_paymntgty, "POST scheduled payments to payment gateway", "https")
Rel(sys_quirc, sys_documentsvc, "POST underwriting documentation", "https")
Rel(sys_quotesvc, sys_documentsvc, "POST|GET quote document", "https")
Rel(sys_quotesvc, sys_notifysvc, "POST notification", "https")
Rel(sys_quotesvc, sys_quirc, "POST quote data", "https")
Rel(sys_sanctionsvc, sys_sanction, "POST sanction request", "https")
Rel(sys_sapiens, sys_policysvc, "POST business event", "https")
Rel(sys_sapiens, sys_pymntsvc, "POST payment event", "https")
Rel(sys_sapiens, sys_quotesvc, "POST business event", "https")
Rel(sys_sapiens, sys_sanctionsvc, "GET sanction response", "https")
Rel(sys_telephony, sys_mediasvc, "POST media", "https")
Rel_L(sys_glextract, sys_sapiens, "GET GL data", "https")
Rel_L(sys_notifysvc, p_lead, "SEND notification", "smtp")
Rel_L(sys_notifysvc, p_member, "SEND notification", "smtp")

SHOW_FLOATING_LEGEND()

@enduml