@startuml Claim Feature Service Integration Container

'title Reserve Estimation Service Integration Container

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include style/sprites.puml
!include style/brand.puml

'Style
'LAYOUT_AS_SKETCH()
'LAYOUT_LANDSCAPE()

System(sys_eis, "EIS", "Tower core insurance system with Policy, Claim and Billing management functionality.", $sprite="blur_on")
System_Boundary(sb1, "Azure Integration Services") {
    System(sys_feature_svc, "Claim Feature Service", "Provides the automation of a feature to be added to the claim.", $tags="new")
    'System(sys_claim_api, "Claim API", "Service that provides business logic for the domain defined by the API", $tags="new")
    'System(sys_resesti_svc, "Claim Reserve Estimation Service", "Provides the calulation to define the claim reserve.", $sprite="calculator*.75", $tags="new")
}
System\(sys_decision_svc, "Decision Service", "Business Rules Engine stores and executes business rules"\)

'Rel(sys_claim_api, sys_eis, "Makes API calls", "JSON/HTTP")
Rel(sys_eis, sys_feature_svc, "Makes API calls", "JSON/HTTP")
'Rel(sys_feature_svc, sys_claim_api, "Makes API calls", "JSON/HTTP")
'Rel(sys_feature_svc, sys_resesti_svc, "Makes API calls", "JSON/HTTP")
Rel(sys_feature_svc, sys_decision_svc, "Makes API calls", "JSON/HTTP")

SHOW_FLOATING_LEGEND()

@enduml