@startuml PPS Integration Landscape
'skinparam monochrome true
'skinparam linetype polyline

'Title "Education Hub Application Landscape"

'!theme C4_cyma from https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/themes/
!theme C4_twoa from https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/themes/

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/sprites.puml
!include https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/brand.puml

'LAYOUT_LANDSCAPE()
'LAYOUT_LEFT_RIGHT()
'LAYOUT_AS_SKETCH()

Person(p_employee, "Registry Kaimahi (employee)", "supports wananga (enrolment) services")
Person(p_teacher,"Kaiako (teacher)", "provides wananga (teaching) services")
Person_Ext(p_student, "Tauira (student)", "tauira seeking Te Wananga o Aotearoa services")

System_Ext(sys_sdr, "Single Data Return (SDR)", "is an electronic database of student enrollment and completion information in New Zealand.")
System_Ext(sys_nzqa, "NZQA", "the definitive source for accurate information about all quality assured qualifications, covering senior secondary school and tertiary education qualifications, and including all qualifications open to international students.")
System_Ext(sys_nsi, "National Student Index (NSI)", "is a database system maintained by the Ministry of Education and is the education sector's core register of learner identity data.")
System_Ext(sys_studylink, "StudyLink", "a program that helps students make educational decisions and achieve their goals by providing financial support and information.")
System_Ext(sys_idcards, "Student ID Card Service", "ID creation services.")
Enterprise_Boundary(e0, "Te Wananga o Aotearoa"){

System(sys_ad, "Active Directory", "identity and access platform")
System(sys_applicationportal, "Online Application Portal", "a digital platform that allows prospective students to apply for admission.", $sprite="web_asset")
System(sys_erp, "ERP", "a software system that integrates and manages core business processes like finance, HR, supply chain, and operations into a single platform.")
System(sys_excel, "Microsoft Excel", "provides reference data.")
System(sys_lms, "LMS", "A Learning Management System (LMS) is a software platform for creating, managing, delivering, and tracking online learning programs.")
System(sys_smc, "Salesforce Marketing Cloud", "provides tools for email marketing, social media management, mobile marketing, SMS, and more.", $sprite="salesforce")
System(sys_sms, "SMS", "Student Management System (SMS) it serves as a centralised hub for managing student information, academic records, attendance, and various other aspects of the educational ecosystem.")
System(sys_ssc, "Salesforce Service Cloud", "is a core component of the Salesforce CRM suite, providing a unified view of customers across various touchpoints.", $sprite="salesforce")
System(sys_tpms, "TPMS","Student Helpdesk Management System")
}

Rel(p_employee, sys_excel, "Uses", "")
Rel(p_employee, sys_nzqa, "GET, PUT accreditation information", "manual")
Rel(p_employee, sys_smc, "Uses", "https")
Rel(p_employee, sys_sms, "Uses", "Citrix")
Rel(p_employee, sys_ssc, "Manually adds prospects", "https")
Rel(p_employee, sys_studylink, "VOS request", "manual")
Rel(p_student, sys_ad, "Authenticates using", "https")
Rel(p_student, sys_applicationportal, "Uses", "https")
Rel(p_student, sys_ssc, "Uses", "https")
Rel(p_teacher, sys_sms, "Uses", "Citrix")
Rel(sys_applicationportal, sys_sms, "Connects to", "jdbc")
Rel(sys_excel, sys_sms, "Programme and course fees", "manual")
Rel(sys_sms, sys_ad, "POST student information", "")
Rel(sys_sms, sys_idcards, "POST student information", "sql agent")
Rel(sys_sms, sys_nsi, "Verify student information", "")
Rel(sys_sms, sys_sdr, "Send student and course information", "ftp")
Rel(sys_tpms, sys_sms, "GET student information", "odbc")
Rel_D(sys_sms, sys_erp, "Sends financial data", "various")
Rel_Neighbor(sys_lms, sys_sms, "Connects to", "https")
Rel_Neighbor(sys_tpms, sys_ad, "POST student information", "")

@enduml