@startuml PPS Integration Landscape
'skinparam monochrome true
'skinparam linetype polyline

'Title "Education Hub Application Landscape"

!theme C4_twoa from https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/themes/

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/sprites.puml
!include https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/brand.puml

'LAYOUT_LANDSCAPE()
'LAYOUT_LEFT_RIGHT()
'LAYOUT_AS_SKETCH()

Person(p_employee, "Registry Kaimahi (employee)", "supports wananga (enrollment) services")
Person(p_teacher,"Kaiako (teacher)", "provides wananga (teaching) services")
Person_Ext(p_student, "tauira (student)", "tauira seeking Te Wananga o Aotearoa services")

System_Boundary(sb0, "Student Management Solution"){
    Container(sys_smsapp, "Student Management Application", "Microsoft Access 2000", "Helps to manage and organise tauira data such as enrolment, attendance, grades, and assessments")
    Container(sys_smssupport, "Student Support Module", "Microsoft Access 2000", "Provides the ability to manage and organise assorted services and resources to help tauira succeed in their academic journey")
    ContainerDb(sys_take2Db, "Take2", "Microsoft SQL 2019", "", $sprite="AzureSqlDatabase")

}

System(sys_101, "101 SIIS", "Provides access to tauira data to internal kaimahi e.g. Tauira Details (addresses etc.), attendance and assessment.")
System(sys_applicationportal, "Online Application Portal", "a digital platform that allows prospective students to apply for admission.", $sprite="web_asset")
System(sys_automation, "Automations", "Automations")
System(sys_dgp, "Dynamics Great Plains", "Finance System")
System(sys_dwh, "TWoA Data Warehouse", "Microsoft SQL ???", "Data Warehouse", $sprite="AzureSqlDatabase")
System(sys_eip, "EIP Fin Debt Mails", "Azure Functions")
'System(sys_excel, "Microsoft Excel", "provides reference data.")
System(sys_glist, "G List", "Graduation List")
System(sys_iqualify, "Akorau", "Tairua facing Learning Management System (LMS) iQualify")
System(sys_keep100, "Keep100", "Assessment results for NZQA")
System(sys_moderation, "Moderation", "Tutor Record Management")
System(sys_moodle, "iAkoranga", "Tairua facing Learning Management System (LMS) Moodle")
System(sys_pams, "PAMS", "Unknown", "Provider Admin Management System")
System(sys_sharepoint, "Rakaunui", "Sharepoint/Intranet")
System(sys_smc, "Salesforce Marketing Cloud", "used to create and manage personalised customer interactions.", $sprite="salesforce")
System(sys_ssc, "Salesforce Service Cloud", "Used to manage the enrolment application processes", $sprite="salesforce")
System(sys_twoawebsite, "TWoA Website", "provides reference data.")
System(sys_whatatuarirau, "Whata Tuarirau", "Tairua Resource Ordering")
System(sys_tpms, "TPMS","Student Helpdesk Management System")

System(sys_ppms, "PPMS", "Microsoft SQL ???", "Microsoft SQL 2019", $sprite="AzureSqlDatabase")

' Relationships
Rel(p_employee, sb0, "Uses", "Citrix")
Rel(p_student, sys_applicationportal, "Uses", "https")
Rel(p_teacher, sb0, "Uses", "Citrix")
Rel(sys_101, sys_take2Db, "Connects to", "???")
Rel(sys_applicationportal, sys_take2Db, "Connects to", "JDBC")
Rel(sys_automation, sys_take2Db, "Connects to", "JDBC")
Rel(sys_eip, sys_take2Db, "Connects to", "???")
Rel(sys_glist, sys_take2Db, "Connects to", "???")
Rel(sys_iqualify, sys_take2Db, "Connects to", "???")
Rel(sys_keep100, sys_take2Db, "Connects to", "???")
Rel(sys_moderation, sys_take2Db, "Connects to", "???")
Rel(sys_moodle, sys_take2Db, "Connects to", "???")
Rel(sys_pams, sys_take2Db, "Connects to", "JDBC")
Rel(sys_smc, sys_take2Db, "Connects to", "???")
Rel(sys_take2Db, sys_dgp, "Connects to", "???")
Rel(sys_take2Db, sys_ppms, "Connects to", "???")
Rel(sys_take2Db, sys_sharepoint, "Connects to", "???")
Rel(sys_tpms, sys_take2Db, "GET student information", "ODBC")
Rel(sys_twoawebsite, sys_take2Db, "Connects to", "JDBC")
Rel(sys_whatatuarirau, sys_take2Db, "Connects to", "JDBC")
Rel_D(sys_smsapp, sys_take2Db, "Connects to", "ODBC")
Rel_D(sys_smssupport, sys_take2Db, "Connects to", "JDBC")
Rel_U(sys_dwh, sys_take2Db, "Connects to", "JDBC")

@enduml