@startuml PPS Integration Landscape
'skinparam monochrome true
'skinparam linetype polyline

'Title "Education Hub Application Landscape"

'!theme C4_cyma from https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/themes/
!theme C4_twoa from https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/themes/

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/sprites.puml
!include https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/brand.puml

'LAYOUT_LANDSCAPE()
'LAYOUT_LEFT_RIGHT()
'LAYOUT_AS_SKETCH()

Person(p_employee, "Registry Kaimahi (employee)", "supports wananga (enrolment) services")
Person(p_teacher,"Kaiako (teacher)", "provides wananga (teaching) services")
Person_Ext(p_student, "Tauira (student)", "tauira seeking Te Wananga o Aotearoa services")
Person_Ext(p_prospect, "Prospect", "prospect seeking Te Wananga o Aotearoa services ")

System_Ext(sys_idcards, "Student ID Card Service", "ID creation services.")
System_Ext(sys_nsi, "National Student Index (NSI)", "is a database system maintained by the Ministry of Education and is the education sector's core register of learner identity data.")
System_Ext(sys_nzqa, "NZQA", "the definitive source for accurate information about all quality assured qualifications, covering senior secondary school and tertiary education qualifications, and including all qualifications open to international students.")
System_Ext(sys_sdr, "Single Data Return (SDR)", "is an electronic database of student enrollment and completion information in New Zealand.")
System_Ext(sys_studylink, "StudyLink", "a program that helps students make educational decisions and achieve their goals by providing financial support and information.")

Enterprise_Boundary(e0, "Te Wananga o Aotearoa"){
    System_Boundary(sb0, "Leraning Management Solution"){
        System(sys_lln, "LLN Assessment tool", "assessment tool is used for literacy and numeracy assessments.")
        System(sys_lms, "Moodle (LMS)", "A Learning Management System (LMS) is a software platform for creating, managing, delivering, and tracking online learning programs.")
        }

    System(sys_ad, "Active Directory", "identity and access platform")
    System(sys_adscss, "Automated Distribution and Customer Support System (ADSCSS)", "used to distribute kete (workbooks and resources) to students.")

    System_Boundary(sb1, "Te Wananga Website"){
        System(sys_applicationportal, "Application Portal", "a digital platform that allows prospective students to apply for admission.", $sprite="web_asset")
        }
    System(sys_voyager, "Library System (Voyager)", "s an integrated library system used by hundreds of libraries, universities and museums around the world.")
    System(sys_tpms, "TPMS","TPMS (student helpdesk management system) pulls student, enrolment and class information from Take2. It also provides AD data to Akonga AD.")
    System(sys_ssm, "Student Support Module", "a tool created to manage and monitor student support provided throughout the organisation.")
    System(sys_ssis101, "SSIS101", "allows students and tutors to update limited student information without physically logging into the Take2 system.")
    System(sys_ssc, "Salesforce Service Cloud", "process online applications and capture expressions of interest (EOI) and lead information from different online channels. It is currently using account and application creation register and student details from Take2.", $sprite="salesforce")
    System(sys_sms, "Take2 (SMS)", "Student Management System (SMS) it serves as a centralised hub for managing student information, academic records, attendance, and various other aspects of the educational ecosystem.")
    System(sys_smc, "Salesforce Marketing Cloud", "provides tools for email marketing, social media management, mobile marketing, SMS, and more.", $sprite="salesforce")
    System(sys_pams, "Provider Administration Management System (PAMS)", "student records are managed, and unit standard assessment sheets are maintained.")
    System(sys_glist, "Graduation List", "uses enrolment data, student details, and completions to determine the graduation list, certificate requests and certificates printed")
    System(sys_excel, "Microsoft Excel", "provides enrollment plan and fees data.")
    System(sys_erp, "ERP", "a software system that integrates and manages core business processes like finance, HR, supply chain, and operations into a single platform.")
    System(sys_echeck, "E-Check", "uses enrolment data, programme code and status information from Take2 to manage the Enrolment checking and validation process.")
    System(sys_dwh, "TWoA Data Warehouse", "")
    }

Rel(p_employee, sys_applicationportal, "Sends student details", "sql agent")
Rel(p_employee, sys_erp, "Submits financial data", "https")
Rel(p_employee, sys_excel, "Uses", "")
Rel(p_employee, sys_nsi, "Verify student information", "")
Rel(p_employee, sys_nzqa, "GET, PUT accreditation information", "manual")
Rel(p_employee, sys_smc, "Uses", "https")
Rel(p_employee, sys_sms, "Extracts financial data, updates student NSI information and NZQA credits, VOS request, loads enrollment plan and fees", "Citrix")
Rel(p_employee, sys_ssc, "Manually adds prospects", "https")
Rel(p_employee, sys_ssm, "Submits Student adviser report by Rohe", "???")
Rel(p_employee, sys_studylink, "VOS request", "manual")
Rel(p_prospect, sys_applicationportal, "Uses", "https")
Rel(p_student, sys_ssis101, "views and updates student information")
Rel(p_teacher, sys_lln, "Uses", "??")
Rel(p_teacher, sys_lms, "Uses", "??")
Rel(p_teacher, sys_pams, "Uses", "??")
Rel(p_teacher, sys_sms, "Uses", "Citrix")
Rel(p_teacher, sys_ssis101, "updates student details and course completion", "https")
Rel(sys_applicationportal, sys_ssc, "Sends online applications", "jdbc")
Rel(sys_pams, sys_sms, "Updates on personal details Course completion", "???")
Rel(sys_sms, p_student, "notifications", "various")
Rel(sys_sms, sys_ad, "POST student information", "sql agent")
Rel(sys_sms, sys_adscss, "POST data", "sql agent")
Rel(sys_sms, sys_dwh, "POST data", "sql agent")
Rel(sys_sms, sys_echeck, "POST enrolment data, programme code and status information", "")
Rel(sys_sms, sys_erp, "POST student course financial details", "manual")
Rel(sys_sms, sys_glist, "POST enrolment data, student details, and completions", "")
Rel(sys_sms, sys_idcards, "POST student information", "sql agent")
Rel(sys_sms, sys_lln, "POST enrolment data, programme code", "manual")
Rel(sys_sms, sys_lms, "POST enrolment data, programme code", "stored procedure")
Rel(sys_sms, sys_sdr, "Send student and course information", "ftp")
Rel(sys_sms, sys_tpms, "POST student information", "sql agent")
Rel(sys_sms, sys_voyager, "POST student information", "ftp")
Rel(sys_ssc, sys_sms, "Enrolment status change updates Programme of interest Student details change updates Personal account", "???")
Rel(sys_ssis101, sys_sms, "Updates on personal details Course completion", "???")

@enduml