@startuml Claim Status Management Service - Container

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include style/sprites.puml
!include style/brand.puml

'Style
'LAYOUT_AS_SKETCH()
'LAYOUT_LANDSCAPE()

'Person_Ext(p_t_customer, "Customer", "Any customer interacting with customer services", $sprite="user")
'System(sys_mytower, "My Tower", "Provides customers the ability to digitally interact with Tower services.", $sprite="web_asset")
System(sys_eis, "EIS", "Tower core insurance system with Policy, Claim and Billing management functionality.", $sprite="blur_on")
System(sys_claimstatusmgmnt_svc, "Incomplete Claim Submission Service", "Provides the business rules to manage the claims submission.", $sprite="AzureLogicApps*.8", $tags="new")
System(sys_notification_svc, "Notification Service", "Tower notification service that sends notifications on the preferred channel. [TBC]", $sprite="email", $tags="tbc")
'System(sys_data_services, "Data Services", "Provides Integration services for Towers systems.", $sprite="snowflake")

'Rel(p_t_customer, sys_mytower, "Manages claims using", "Visits pages")
'Rel(sys_mytower, sys_eis, "Makes API calls to submit claim", "JSON/HTTP")
Rel(sys_claimstatusmgmnt_svc, sys_eis, "Makes API calls using", "JSON/HTTP")
'Rel(sys_claimstatusmgmnt_svc, sys_data_services, "Queries data using", "SQL")
Rel(sys_eis, sys_notification_svc, "Sends notifications using", "JSON/HTTP")

SHOW_FLOATING_LEGEND()

@enduml