@startuml eis platform integration container alt

!theme C4_cyma from https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/themes/

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/sprites.puml
!include https://raw.githubusercontent.com/david-rawnsley-cyma/cyma/main/style/brand.puml

LAYOUT_LANDSCAPE()
LAYOUT_LEFT_RIGHT()
'LAYOUT_AS_SKETCH()

Person_Ext(p_t_customer, "Customer", "Any customer interacting with customer services", $sprite="user")
System_Boundary(sb1, "EIS") {
    System(sys_eis, "EIS", "Tower core insurance system with Policy, Claim and Billing management functionality.")
    System(sys_dxp, "DXP", "Tower core insurance system API ecosystem.")
}
System_Boundary(sb3, "Digital Experience") {
    System(sys_mytower, "My Tower", "Provides customers the ability to digitally interact with Tower services.", $sprite="web_asset")
    System(sys_digiexp_api, "Digital Experience API", "Provides integration to Towers Core Insurance services.", $sprite="dotnet")
    System(sys_digiclaim_api, "Digital Claims API", "Provides integration to Towers Core Insurance services.", $sprite="dotnet")
    System_Ext(sys_digicustomer_api, "Digital Customer API", "Provides integration to Towers Core Insurance services.", $sprite="dotnet")
    System_Ext(sys_digipolicy_api, "Digital Policy API", "Provides integration to Towers Core Insurance services.", $sprite="dotnet")
}
System(sys_pltfm_svc, "Assessor Platform Service", "Provides integration to the Platforms for Motor or House and Contents.", $sprite="kotlin*.5", $tags="new")
System(sys_allocation_svc, "Allocation Service", "Calculates the resource to be assigned to the claim.", $sprite="hands_helping", $tags="new")
System(sys_resesti_svc, "Claim Reserve Estimation Service", "Provides the calulation to define the claim reserve.", $sprite="calculator*.75", $tags="new")
System(sys_fis_svc, "Fraud Indicator Service (FIS)", "Provides fraud indicators to Towers internal services.", $sprite="kotlin*.5")
System(sys_ics_svc, "Investigation Case Service (ICS)", "Provides integration to Towers invetigation services.", $sprite="kotlin*.5")
System(sys_recovery_svc, "Recovery Service", "Create and track recovery records for claims which have 3rd party liability", $sprite="kotlin*.5")

Rel(p_t_customer, sys_mytower, "Visits pages", "HTTP")
Rel(sys_allocation_svc, sys_dxp, "Makes API POST/PATCH/PUT calls", "JSON/HTTP")
Rel(sys_digiclaim_api, sys_dxp, "Makes API calls", "JSON/HTTP")
Rel(sys_digicustomer_api, sys_dxp, "Makes API calls", "JSON/HTTP")
Rel(sys_digiexp_api, sys_digiclaim_api, "Makes API calls", "JSON/HTTP")
Rel(sys_digiexp_api, sys_digicustomer_api, "Makes API calls", "JSON/HTTP")
Rel(sys_digiexp_api, sys_digipolicy_api, "Makes API calls", "JSON/HTTP")
Rel(sys_digipolicy_api, sys_dxp, "Makes API calls", "JSON/HTTP")
Rel(sys_dxp, sys_eis, "Makes API calls", "JSON/HTTP")
Rel(sys_eis, sys_allocation_svc, "Makes API calls", "JSON/HTTP")
Rel(sys_eis, sys_fis_svc, "Makes API calls", "JSON/HTTP")
Rel(sys_eis, sys_ics_svc, "Makes API calls", "JSON/HTTP")
Rel(sys_eis, sys_pltfm_svc, "Makes API calls", "JSON/HTTP")
Rel(sys_eis, sys_recovery_svc, "Makes API calls", "JSON/HTTP")
Rel(sys_eis, sys_resesti_svc, "Makes API calls", "JSON/HTTP")
Rel(sys_fis_svc, sys_dxp, "Makes API POST/PATCH/PUT calls", "JSON/HTTP")
Rel(sys_ics_svc, sys_dxp, "Makes API POST/PATCH/PUT calls", "JSON/HTTP")
Rel(sys_ics_svc, sys_fis_svc, "Makes API calls", "JSON/HTTP")
Rel(sys_mytower, sys_digiexp_api, "Makes API calls", "JSON/HTTP")
Rel(sys_pltfm_svc, sys_dxp, "Makes API POST/PATCH/PUT calls", "JSON/HTTP")
Rel(sys_recovery_svc, sys_dxp, "Makes API POST/PATCH/PUT calls", "JSON/HTTP")
Rel(sys_recovery_svc, sys_eis, "Makes API calls", "JSON/HTTP")
Rel(sys_resesti_svc, sys_dxp, "Makes API POST/PATCH/PUT calls", "JSON/HTTP")

SHOW_FLOATING_LEGEND()

@enduml