@startuml Text-to-Speech Future State Service

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include style/sprites.puml
!include style/brand.puml

LAYOUT_LANDSCAPE()

Person_Ext(p_t_customer, "Customer", "Any customer interacting with customer services", $sprite="user")
Person(p_t_emp, "Tower Employee", "Any employee entitled to request IVR changes", $sprite="users")
Person(p_market, "Marketing", "Ensures IVR changes conform to Marketing and Brand requirements", $sprite="users")
Person(p_ivradmin, "IVR Administrator", "Performs administrative functions within the IVR solution", $sprite="user")
Person(sys_azure_vs, "Azure Audio Content Creation tool", "A Speech service feature that converts text to lifelike speech", $sprite="microphone")
System(sys_mitel, "Mitel", "Provides call center, unified communications and cloud communications solutions.", $sprite="blur_on")

Rel_R(p_t_emp, p_market, "Requests changes to IVR", "email")
Rel_D(p_market, p_ivradmin, "Requests changes to IVR", "email")
Rel_R(p_t_customer, sys_mitel, "Calls Tower", "pstn")
Rel_L(p_ivradmin, sys_mitel, "Manages IVR")
Rel_D(p_ivradmin, sys_azure_vs, "Provides script", "text")

SHOW_FLOATING_LEGEND()
@enduml